### ISSUE TITLE
CLI crashing and no results showing up

### ISSUE THREAD

**Issue by ThunderStruct** [jacobp100/recora#1]
Hi!

First off, just by skimming through the code I must say you've done a great job! It's pretty impressive that you built it based on a lexer and a parser.

I'm not sure if it's just me, but I tried running Recora (by cloning the repo and running `npm install` and `npm run cli`) and it keeps crashing. The inputs I tried were math expressions, and I noticed that it only crashes when I use any integers. If I used plain text expressions (such as "one plus one"), it outputs "no result".

What am I doing wrong?

Thanks!

**Comment by jacobp100** [comment]
Do you get an error message when it crashes?

`one plus one` won’t work though, it can’t parse numbers written in word form yet (although the `plus` part should work)

**Comment by ThunderStruct** [comment]
Yes an error is thrown from `readline.js`. 

Here's a screenshot of the error stack trace when I tried one of the example inputs (`1 meter to yards`)

![screenshot](https://i.imgur.com/LbUpopo.png)

**Comment by jacobp100** [comment]
Looks like Lodash pushed a breaking change under a patch version 🙁

Should work now!

**Comment by ThunderStruct** [comment]
Brilliant! I just checked out the latest commit and it works perfectly well...
Thank you so much for you support! Have a great day 😄
